@baseURL = http://localhost:3333

@module = questions

@authToken = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseURL}}/{{module}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Another question",
  "content": "I'm trying to create a question using the API, but I'm not sure how to do it. Can you help me?"
}

###

# @name fetch_recent_questions
GET {{baseURL}}/{{module}}?page=1
Authorization: Bearer {{authToken}}